# Generated by Django 5.2.4 on 2025-08-18 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='oficina.oficina', verbose_name='Oficina asignada')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
